[build]
  command = "yarn build"
  publish = "client/build"
  functions = "functions"
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  status = 200
